class AddIndexToAttachProducts < ActiveRecord::Migration
  def self.up
    add_index :attached_products, :product_id
    add_index :attached_products, :machine_id
    add_index :bins, :bin_type_id
    add_index :bins, :bin_status_id
    add_index :bin_clearing_records, :bin_id
    add_index :bin_clearing_records, :employee_id
    add_index :cold_stores, :procedure_transaction_id
    add_index :cold_stores, :administrator_id
    add_index :cold_stores, :product_id
    add_index :cold_store_accounts, :product_id
    add_index :containers, :product_id
    add_index :containers, :bin_type_id
    add_index :employees, :department_id
    add_index :input_machines, :machine_id
    add_index :input_machines, :material_input_id
    add_index :login_records, :employee_id
    add_index :login_records, :machine_id
    add_index :machine_downtimes, :machine_id
    add_index :machine_downtimes, :employee_id
    add_index :machine_downtimes, :routing_id
    add_index :machine_downtimes, :routing_process_id
    add_index :machine_downtimes, :routing_procedure_id
    add_index :machine_downtimes, :bin_id
    add_index :machine_downtimes, :bin_type_id
    add_index :machine_downtimes, :product_id
    add_index :machine_downtimes, :machine_down_reason_id
    add_index :machine_downtimes, :container_id
    add_index :material_inputs, :material_id
    add_index :operators, :machine_id
    add_index :operators, :employee_id
    add_index :procedure_machines, :routing_procedure_id
    add_index :procedure_machines, :machine_id
    add_index :procedure_machines, :routing_id
    add_index :procedure_products, :routing_process_id
    add_index :procedure_products, :product_id
    add_index :procedure_transactions, :routing_procedure_id
    add_index :procedure_transactions, :employee_id
    add_index :procedure_transactions, :product_id
    add_index :procedure_transactions, :machine_id
    add_index :procedure_transactions, :routing_id
    add_index :procedure_transactions, :routing_process_id
    add_index :procedure_transactions, :bin_id
    add_index :procedure_transactions, :bin_type_id
    add_index :procedure_transactions, :container_id
    add_index :procedure_transactions, :reject_code_id
    add_index :procedure_transactions, :shift_id
    add_index :routing_procedures, :routing_id
    add_index :routing_procedures, :routing_process_id
    add_index :shift_items, :machine_id
    add_index :shift_items, :shift_id
    add_index :working_states, :product_id
    add_index :working_states, :bin_id
    add_index :working_states, :routing_procedure_id
    add_index :working_states, :employee_id
    add_index :working_states, :machine_id
        
  end

  def self.down
    remove_index :attached_products, :product_id
    remove_index :attached_products, :machine_id
    remove_index :bins, :bin_type_id
    remove_index :bins, :bin_status_id
    remove_index :bin_clearing_records, :bin_id
    remove_index :bin_clearing_records, :employee_id
    remove_index :cold_stores, :procedure_transaction_id
    remove_index :cold_stores, :administrator_id
    remove_index :cold_stores, :product_id
    remove_index :cold_store_accounts, :product_id
    remove_index :containers, :product_id
    remove_index :containers, :bin_type_id
    remove_index :employees, :department_id
    remove_index :input_machines, :machine_id
    remove_index :input_machines, :material_input_id
    remove_index :login_records, :employee_id
    remove_index :login_records, :machine_id
    remove_index :machine_downtimes, :machine_id
    remove_index :machine_downtimes, :employee_id
    remove_index :machine_downtimes, :routing_id
    remove_index :machine_downtimes, :routing_process_id
    remove_index :machine_downtimes, :routing_procedure_id
    remove_index :machine_downtimes, :bin_id
    remove_index :machine_downtimes, :bin_type_id
    remove_index :machine_downtimes, :product_id
    remove_index :machine_downtimes, :machine_down_reason_id
    remove_index :machine_downtimes, :container_id
    remove_index :material_inputs, :material_id
    remove_index :operators, :machine_id
    remove_index :operators, :employee_id
    remove_index :procedure_machines, :routing_procedure_id
    remove_index :procedure_machines, :machine_id
    remove_index :procedure_machines, :routing_id
    remove_index :procedure_products, :routing_process_id
    remove_index :procedure_products, :product_id
    remove_index :procedure_transactions, :routing_procedure_id
    remove_index :procedure_transactions, :employee_id
    remove_index :procedure_transactions, :product_id
    remove_index :procedure_transactions, :machine_id
    remove_index :procedure_transactions, :routing_id
    remove_index :procedure_transactions, :routing_process_id
    remove_index :procedure_transactions, :bin_id
    remove_index :procedure_transactions, :bin_type_id
    remove_index :procedure_transactions, :container_id
    remove_index :procedure_transactions, :reject_code_id
    remove_index :procedure_transactions, :shift_id
    remove_index :routing_procedures, :routing_id
    remove_index :routing_procedures, :routing_process_id
    remove_index :shift_items, :machine_id
    remove_index :shift_items, :shift_id
    remove_index :working_states, :product_id
    remove_index :working_states, :bin_id
    remove_index :working_states, :routing_procedure_id
    remove_index :working_states, :employee_id
    remove_index :working_states, :machine_id
  end
end
